[package]
name = "rtp-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-cursor = "0.1.1"
anyhow = "1"
bitvec = "1.0.1"
bytes = "1.6.0"
