[package]
name = "rtp_parse"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
packet_parsing = { path = "../packet_parsing" }
bitbuffer = { git = "https://github.com/bbaldino/bitbuffer" }
thiserror = "1.0"
